version: '2'
services:
  web:
    tty: true
    image: odoo:9.0
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
    #   - ./.config:/etc/odoo
      - ./:/mnt/extra-addons
    command: openerp-server --log-level=debug  # -i woodwerk --test-enable --stop-after-init -d wwtests
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
